/**
 * SynSync Pro — Sensorimotor Rhythm + Mu Suppression Spec
 * =========================================================
 * Protocol: SMR-Mu — Sensorimotor Rhythm Motor Learning (Grade B)
 *
 * @version 2.0.0
 */

import type { ProtocolSpec } from '../../../audio/dsp/types';
import { phase } from '../../../audio/dsp/phase-builder';
import { CARRIERS, DSP_DEFAULTS } from '../../../audio/dsp/constants';

export const smrMu: ProtocolSpec = {
  id: 'smr_mu',
  name: 'SMR-Mu — Sensorimotor Rhythm + Mu Suppression',
  category: 'performance_focus',
  version: '2.0.0',
  durationSeconds: 900,
  evidenceLevel: 'II',
  citations: [
    'Egner, T. & Gruzelier, J.H. (2004) "EEG biofeedback of low beta band components: Frequency-specific effects." NeuroReport 15(4):683-686.',
    'Arns, M. et al. (2009) "Efficacy of neurofeedback treatment in ADHD." Clin. EEG Neurosci. 40(3):180-189.',
    'Nakata, H. et al. (2018) "Effects of SMR neurofeedback training on H-reflex." Exp. Brain Res. 236(9):2389-2398.',
    'Zich, C. et al. (2023) "Mu suppression and motor learning: A systematic review." Neurosci. Biobehav. Rev.',
  ],
  usageGoal: 'Enhance motor skill acquisition, impulse control, and focused calm by entraining the 12–15 Hz sensorimotor rhythm. Simultaneously suppresses mu (10 Hz) desynchronisation to prime mirror neuron circuits for motor learning.',
  algorithmDescription: 'Three-phase protocol: relaxation base (alpha 10 Hz, 2 min) → SMR induction (binaural 13 Hz over sensorimotor cortex carrier, 8 min) → SMR consolidation with mu suppression overlay (13 Hz dominant, 10 Hz counter-phase overlay, 5 min). All audio-only, no visual flicker.',
  researchContext: 'SMR (12–15 Hz) is generated by thalamo-cortical sensorimotor circuits during still-but-ready states. Egner & Gruzelier (2004) showed SMR training enhances attentional performance. Mu rhythm (8–12 Hz) desynchronises during motor observation and imagery — suppression marks mirror neuron engagement. Combined SMR+mu-suppression primes both motor execution (SMR) and observational motor learning (mu).',
  targetBands: ['smr', 'alpha'],
  neurochemistryTargets: ['GABA ↑ (motor cortex inhibitory control)', 'Dopamine D1 ↑ (striatal reward-motor)', 'Serotonin ↑ (impulse regulation)'],
  phases: [
    phase(0, 'Relaxation Base')
      .duration(120)
      .beat(10)
      .carrier(CARRIERS.warm)
      .noise('pink', 0.06)
      .carrierOctaves({ enabled: true, octavesAbove: 1, octavesBelow: 1, gainRolloff: 0.7, detuneSpread: 4 })
      .purpose('Quiet default-mode noise; relax motor cortex; prepare sensorimotor circuits for SMR induction')
      .build(),

    phase(1, 'SMR Induction')
      .duration(480)
      .beat(13)
      .carrier(CARRIERS.neutral)
      .noise('pink', 0.05)
      .carrierOctaves({ enabled: true, octavesAbove: 1, octavesBelow: 1, gainRolloff: 0.65, detuneSpread: 5 })
      .purpose('Drive 13 Hz SMR; motor cortex stillness + ready-state; reduces impulsivity, increases fine motor control')
      .build(),

    phase(2, 'SMR–Mu Integration')
      .duration(300)
      .beat(13)
      .carrier(CARRIERS.neutral)
      .noise('pink', 0.04)
      .overlays([10], 0.07)
      .carrierOctaves({ enabled: true, octavesAbove: 1, octavesBelow: 1, gainRolloff: 0.65, detuneSpread: 5 })
      .stochasticJitter(8)
      .purpose('SMR sustained while 10 Hz overlay supports mu-band awareness; motor imagery consolidation; skill encoding window')
      .build(),
  ],
  breathwork: {
    name: 'Still Warrior Breath',
    ratio: [4, 4, 4, 4],
    description: 'Box breathing to support motor stillness and autonomic balance during SMR entrainment.',
    cycleDuration: 16,
    syncToBeat: false,
  },
  mantra: {
    phonetic: 'SO HUM',
    pronunciation: 'Soh-hum',
    tonality: 'Steady, even',
    meaning: 'I am — present, still, ready',
    repeatInterval: 13,
    delivery: 'internal',
  },
  contraindications: {
    absolute: [],
    relative: ['Parkinson\'s disease (SMR disrupted at baseline — consult neurologist)', 'Narcolepsy (may intensify drowsiness)'],
    drugInteractions: ['Beta-blockers reduce SMR amplitude; reduced efficacy expected'],
    specialPopulations: ['Athletes: excellent adjunct to sport-specific practice; use before/during skill drills'],
  },
  expectedTimeline: 'Acute: calmer motor control within 15 min. Cumulative (4 weeks): measurable fine motor improvement, reduced impulsive errors.',
  frequencyOfUse: '4–5x per week; ideally before or during motor skill practice.',
  optimalTiming: 'Before sports training, music practice, surgical/procedural rehearsal, or exam prep',
  masterGain: DSP_DEFAULTS.masterGain,
  sampleRate: 48000,
  bitDepth: 24,
  globalOctaveLayers: true,
};

export const SMR_MU_SPECS: ProtocolSpec[] = [smrMu];
